USE [master]
GO

/****** Object:  Database [BashNipi2]    Script Date: 30.08.2021 3:39:30 ******/
CREATE DATABASE [BashNipi2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BashNipi2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BashNipi2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BashNipi2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BashNipi2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BashNipi2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BashNipi2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BashNipi2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BashNipi2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BashNipi2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BashNipi2] SET ARITHABORT OFF 
GO

ALTER DATABASE [BashNipi2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BashNipi2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BashNipi2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BashNipi2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BashNipi2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BashNipi2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BashNipi2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BashNipi2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BashNipi2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BashNipi2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BashNipi2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BashNipi2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BashNipi2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BashNipi2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BashNipi2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BashNipi2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BashNipi2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BashNipi2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BashNipi2] SET  MULTI_USER 
GO

ALTER DATABASE [BashNipi2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BashNipi2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BashNipi2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BashNipi2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BashNipi2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BashNipi2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BashNipi2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BashNipi2] SET  READ_WRITE 
GO

USE [BashNipi2]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[objectB]') AND type in (N'U'))
DROP TABLE [dbo].[objectB]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Project]') AND type in (N'U'))
DROP TABLE [dbo].[Project]
GO

/****** Object:  Table [dbo].[Project]    Script Date: 25.08.2021 15:22:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Project](
	[Id] [int] NOT NULL,
	[ProjectName] [nvarchar](30) NOT NULL,
	[CreateData] [datetime] NOT NULL,
	[ChangeData] [datetime] NOT NULL,
 CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [dbo].[object]    Script Date: 25.08.2021 11:09:46 ******/


/****** Object:  Table [dbo].[object]    Script Date: 25.08.2021 11:09:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[objectB](
	[Id] [int] NOT NULL,
	[ProjectId] [int] NOT NULL,
	[objectName] [nvarchar](30) NOT NULL,
	[CreateData] [datetime] NOT NULL,
	[ChangeData] [datetime] NOT NULL,
 CONSTRAINT [PK_objectB] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[objectB]  WITH CHECK ADD  CONSTRAINT [FK_objectB_Project] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Project] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[objectB] CHECK CONSTRAINT [FK_objectB_Project]

GO

INSERT INTO [dbo].[Project]
           ([Id]
           ,[ProjectName]
           ,[CreateData]
           ,[ChangeData])
     VALUES
           ('1' ,'Нефтепровод',GETDATE(),GETDATE()),
		   ('2' ,'Автодорога',GETDATE(),GETDATE()),
		   ('3' ,'Кустовая площадка ',GETDATE(),GETDATE())
		  
GO

INSERT INTO [dbo].[objectB]
           ([Id]
           ,[ProjectId]
           ,[objectName]
           ,[CreateData]
           ,[ChangeData])
     VALUES
           ('11','1' ,'Прожекторная площадка',GETDATE(),GETDATE()),
		   ('12','2' ,'Дренажная ёмкость',GETDATE(),GETDATE()),
		   ('13','3' ,'Нужная штука',GETDATE(),GETDATE()),
		   ('22','2' ,'Штуковкина',GETDATE(),GETDATE()),
		   ('23','2' ,'Насос',GETDATE(),GETDATE()),
		   ('32','3' ,'Ну очень нужная штука',GETDATE(),GETDATE())

GO
